### ISSUE TITLE
Error on computing RAS Score

### ISSUE THREAD

**Issue by arianlundberg** [BIMIB-DISCo/MaREA#3]
Dear Davide/MaREA developers,

I attempted to run your tool on MATLAB on my local machine. When generating a metabolic model using either the Core model or Recon2.2, I encountered a warning indicating that a few genes were not found in the dataset. My understanding from the issue reported here, is that I can safely ignore this warning. However, in the subsequent step involving RAS computing, I encountered multiple errors that led to the program halting at "Data computed: 0%."

I would appreciate if you could help me figure it out. 
Thanks! 

Here are the errors:: 

```
Error using getScore>resolveRules
Undefined function 'nanmin' for input arguments of type 'double'.

Error in getScore (line 24)
RAS = resolveRules(ruleParsed);

Error in getDataScored (line 52)
        parfor i=1:nRxn

Error in MaREA/ComputeRASButtonPushed (line 344)
                            app.datasetsStr.(app.DatasetsListBox.Value{i}).datasetSCORE = getDataScored(app.metModel, app.datasetsStr.(app.DatasetsListBox.Value{i}).datasetFilt.(1), app.datasetsStr.(app.DatasetsListBox.Value{i}).datasetFilt{:, colS:end}, app.datasetsStr.(app.DatasetsListBox.Value{i}).datasetFilt.Properties.VariableNames(colS:end), true);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using appdesservices.internal.interfaces.model.AbstractModel/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.
```

**Comment by kiaradamiani** [comment]
Dear Arian,
we recommend using the Galaxy version of the tool that you can use here: http://marea4galaxy.cloud.ba.infn.it/galaxy <http://marea4galaxy.cloud.ba.infn.it/galaxy>
You can find the publication here: https://www.sciencedirect.com/science/article/pii/S2001037019304659
Best regards,
Chaira
_________________
Chiara Damiani, Ph.D.
Associate Professor in Computer Science
Department of Biotechnology and Biosciences
University of Milan Bicocca 
Building U3 - Room 3014 - Piazza Della Scienza 4 - Milan (MI) 
phone: +39 02 64483402
mail: ***@***.***
Webpage: https://sites.google.com/view/chiaradamiani/

**Comment by arianlundberg** [comment]
Thanks! Galaxy version worked perfectly :)
